config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get :favoritings
      get :entries
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  
  resources :topics do
    member do
      resources :posts
    end
  end
  
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  
end

app/models/topic.rb
class Topic < ApplicationRecord
  mount_uploader :picture, PictureUploader
  
  scope :get_by_title, ->(title) {
  where("title like ?", "%#{title}%")
  }
  
  belongs_to :user
  has_many :posts, dependent: :delete_all
  
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 255 }
  validates :picture, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :destroy]
  
  def index
    if logged_in?
      @user = current_user
      @topic = current_user.topics.build  # form_for 用
      @topics = Topic.all.order('created_at DESC').page(params[:page])
      
    if params[:title].present? 
      @topics = @topics.get_by_title params[:title]
    end
    
    @new_topics = Topic.all.order('created_at DESC').limit(5)
    @ranking_counts = Post.ranking
    @ranking_topics = Topic.find(@ranking_counts.keys)
    @rankingtop_counts = Post.rankingtop
    @rankingtop_topics = Topic.find(@rankingtop_counts.keys)

    end
  end

  def show
    @topic = Topic.find(params[:id])
    @new_topics = Topic.all.order('created_at DESC').limit(5)
    @post = @topic.posts.build
    @posts = @topic.posts.all.order('created_at DESC').page(params[:page])

    @ranking_counts = Post.ranking
    @ranking_topics = Topic.find(@ranking_counts.keys)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.build(topic_params)

    if @topic.save
      flash[:success] = 'トピックが投稿されました'
      redirect_to topics_url
    else
      flash.now[:danger] = 'トピックが投稿されませんでした'
      render :new
    end
    
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    if @topic.update(topic_params)
      flash[:success] = 'トピックが更新されました'
      redirect_to @topic
    else
      flash.now[:danger] = 'トピックは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    flash[:success] = 'トピックを削除しました。'
    redirect_to topics_url
  end
  
  private

  def topic_params
    params.require(:topic).permit(:title, :content, :picture)
  end
  
  def correct_user
    @topic = current_user.topics.find_by(id: params[:id])
    unless @topic
      redirect_to root_url
    end
  end
end

app/views/topics/_new_topics.html.erb
<% if topics.present? %>
  <% topics.each do |topic| %>
    <div class="tab-pane" id="reviews">
      <div class="comments reviews">
        <div class="comment clearfix">
          <div class="comment-avatar">
            <%=  link_to image_tag(topic.picture, size: 100), topic_path(topic) %>
          </div>
          <div class="comment-content clearfix">
            <div class="comment-author font-alt">
              <%= topic.title %>
            </div>
            <div class="comment-body">
              <p><%= topic.content %></p>
            </div>
            <div class="comment-meta font-alt">
              <%= topic.created_at.strftime('%Y/%m/%d %H:%M') %> - <span><%= @ranking_counts[topic.id] %>コメント</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%#= paginate @topics %>
<% end %>

app/views/topics/_ranking_topics.html.erb
<% if topics.present? %>
  <% topics.each do |topic| %>
    <div class="tab-pane" id="reviews">
      <div class="comments reviews">
        <div class="comment clearfix">
          <div class="comment-avatar">
            <%=  link_to image_tag(topic.picture, size: 100), topic_path(topic) %>
          </div>
          <div class="comment-content clearfix">
            <div class="comment-author font-alt">
              <%= topic.title %>
            </div>
            <div class="comment-body">
              <p><%= topic.content %></p>
            </div>
            <div class="comment-meta font-alt">
              <%= topic.created_at.strftime('%Y/%m/%d %H:%M') %> - <span><%= @ranking_counts[topic.id] %>コメント</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%#= paginate @topics %>
<% end %>

app/views/topics/edit.html.erb
<% content_for :cover do %>
  <section class="module bg-dark-30 about-page-header" data-background="assets/images/about_bg.jpg">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h1 class="module-title font-alt mb-0">Forms</h1>
        </div>
      </div>
    </div>
  </section>
<% end %>

<section class="module">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <h4 class="font-alt mb-0">トピックの編集</h4>
        <hr class="divider-w mt-10 mb-20">
          <%= form_for(@topic) do |f| %>
            <div class="form-group">
              <%= f.label :title, 'タイトル', class: 'sr-only' %>
              <%= f.text_field :title, class: 'form-control', placeholder: 'タイトルを書く' %>
            </div>
            <div class="form-group">
              <%= f.label :content, '内容', class: 'sr-only' %>
              <%= f.text_area :content, class: 'form-control', placeholder: '本文を書く', :rows => "4" %>
            </div>
            <div class="form-group">
              <%= f.label :picture, '画像', class: 'sr-only' %>
              <%= f.file_field :picture, id: :topic_picture %>
              <%= f.hidden_field :picture_cache %>
            </div>
            <%= f.submit 'トピックを編集する', class: 'btn btn-round btn-d' %>
          <% end %>
      </div>
    </div>
  </div>
</section>

app/views/topics/index.html.erb
<% content_for :cover do %>
<section class="module bg-dark-30 about-page-header" data-background="assets/images/about_bg.jpg">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <h1 class="module-title font-alt mb-0">Tabs &amp; Accordions</h1>
      </div>
    </div>
  </div>
</section>
<% end %>

<section class="module">
  <div class="container">
    <div class="row">
      <div class="col-sm-8">
        <h4 class="font-alt mb-0">Topics</h4>
        <hr class="divider-w mt-10 mb-20">
        <div role="tabpanel">
          <% if @topics %>
            <ul class="nav nav-tabs font-alt" role="tablist">
              <li class="active"><a href="#new" data-toggle="tab">新着トピック</a></li>
              <li><a href="#ranking" data-toggle="tab">人気トピック</a></li>
            </ul>
            
            <div class="tab-content">
              <div class="tab-pane active" id="new">
                <%= render 'new_topics', topics: @topics %>
              </div>
              
              <div class="tab-pane" id="ranking">
                  <%= render 'ranking_topics', topics: @rankingtop_topics %>
              </div>
                
            </div>
          <% end %>
        </div>
        
        <div class="comment-form">
          <h4 class="comment-form-title font-alt">トピックの投稿</h4>
          <%= form_for(@topic) do |f| %>
            <div class="form-group">
              <%= f.label :title, 'タイトル', class: 'sr-only' %>
              <%= f.text_field :title, class: 'form-control', placeholder: 'タイトルを書く' %>
            </div>
            <div class="form-group">
              <%= f.label :content, '内容', class: 'sr-only' %>
              <%= f.text_area :content, class: 'form-control', placeholder: '本文を書く', :rows => "4" %>
            </div>
            <div class="form-group">
              <%= f.label :picture, '画像', class: 'sr-only' %>
              <%= f.file_field :picture, id: :topic_picture %>
              <%= f.hidden_field :picture_cache %>
            </div>
            <%= f.submit 'トピックを投稿する', class: 'btn btn-round btn-d' %>
          <% end %>
        </div>
      </div>
      
      
      <%# サイドバー %>
      <div class="col-sm-4 col-md-3 col-md-offset-1 sidebar">
        <div class="widget">
          <form role="form">
            <div class="search-box">
                <%= form_tag(topics_path, method: "get") do %>
                  <div class="input-group">
                    
                  	<%= text_field_tag :title, params[:title], class: 'form-control', placeholder: "トピックを検索" %>
                  	<span class="input-group-btn">
                      <%= button_tag( class: "btn btn-default") do %>
                        <%= content_tag(:i, '', class: 'fa fa-search') %>
                      <% end %>
                      
                  	  <%#= submit_tag '検索', class: 'btn btn-default' %>
                  	  
                  	</span>
                  </div>
                <% end %>
            </div>
          </form>
        </div>
        
        <div class="widget">
          <h5 class="widget-title font-alt">人気トピック</h5>
            <ul class="widget-posts">
              <% if @ranking_topics.present? %>
                <% @ranking_topics.each_with_index do |topic, index| %>
                  <li class="clearfix">
                    <div class="widget-posts-image">
                      <%=  link_to image_tag(topic.picture, size: 100), topic_path(topic) %>
                    </div>
                    <div class="widget-posts-body">
                      <div class="widget-posts-title">
                        <%= topic.title %>
                      </div>
                      <div class="widget-posts-meta">
                        <%= @ranking_counts[topic.id] %>コメント
                      </div>
                    </div>
                  </li>
                <% end %>
              <% end %>
            </ul>
        </div>
        
        <div class="widget">
          <h5 class="widget-title font-alt">新着トピック</h5>
            <ul class="widget-posts">
              <% if @new_topics.present? %>
                <% @new_topics.each do |topic| %>
                  <li class="clearfix">
                    <div class="widget-posts-image">
                      <%=  link_to image_tag(topic.picture, size: 100), topic_path(topic) %>
                    </div>
                    <div class="widget-posts-body">
                      <div class="widget-posts-title">
                        <%= topic.title %>
                      </div>
                      <div class="widget-posts-meta">
                        <%= topic.created_at.strftime('%Y/%m/%d %H:%M') %>
                      </div>
                    </div>
                  </li>
                <% end %>
              <% end %>
            </ul>
        </div>
        
      </div>
      <%# サイドバーここまで %>
      
    </div>
  </div>
</section>

app/views/topics/new.html.erb
<% content_for :cover do %>
  <section class="module bg-dark-30 about-page-header" data-background="assets/images/about_bg.jpg">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h1 class="module-title font-alt mb-0">Forms</h1>
        </div>
      </div>
    </div>
  </section>
<% end %>

<section class="module">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <h4 class="font-alt mb-0">トピックの投稿</h4>
        <hr class="divider-w mt-10 mb-20">
          <%= form_for(@topic) do |f| %>
            <div class="form-group">
              <%= f.label :title, 'タイトル', class: 'sr-only' %>
              <%= f.text_field :title, class: 'form-control', placeholder: 'タイトルを書く' %>
            </div>
            <div class="form-group">
              <%= f.label :content, '内容', class: 'sr-only' %>
              <%= f.text_area :content, class: 'form-control', placeholder: '本文を書く', :rows => "4" %>
            </div>
            <div class="form-group">
              <%= f.label :picture, '画像', class: 'sr-only' %>
              <%= f.file_field :picture, id: :topic_picture %>
              <%= f.hidden_field :picture_cache %>
            </div>
            <%= f.submit 'トピックを投稿する', class: 'btn btn-round btn-d' %>
          <% end %>
      </div>
    </div>
  </div>
</section>

app/views/topics/show.html.erb
<section class="module-small">
  <div class="container">
    <div class="row">
      <div class="col-sm-8">
        <div class="post">
          <div class="post-thumbnail">
            <%= image_tag @topic.picture %>
          </div>
          <div class="post-header font-alt">
            <h1 class="post-title">
              <%= @topic.title %>
            </h1>
            <div class="post-meta">
              <%= link_to @topic.user.name, user_path(@topic.user) %> | <%= @topic.created_at.strftime('%Y/%m/%d %H:%M') %> | <%= @ranking_counts[@topic.id] %> Comments | <%= link_to '一覧に戻る', topics_path %>
              <% if current_user == @topic.user %>
                <%= link_to ' | 編集', edit_topic_path(@topic) %>
                <%= link_to ' | 削除', @topic, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
              <% end %>
            </div>
            <%= render 'favorites/favorite_button', topic: @topic  %>
          </div>
          <div class="post-entry">
            <p><%= @topic.content %></p>
          </div>
        </div>
          
        <%= render 'posts/posts', posts: @posts %>
          
        <div class="comment-form">
          <h4 class="comment-form-title font-alt">コメントを投稿する</h4>
          <%= form_for(@post, remote: true) do |f| %>
            <div class="form-group">
              <%= f.label :comment, 'コメント', class: 'sr-only' %>
              <%= f.text_area :comment, class: 'form-control', placeholder: 'コメントを書く', :rows => "4" %>
            </div>
            <%#= <div class="form-group"> %>
              <%#= f.label :photo, '画像', class: 'sr-only' %>
              <%#= f.file_field :photo, id: :comment_photo %>
              <%#= f.hidden_field :photo_cache %>
            <%#= </div> %>
            <%= f.hidden_field :parent_id %>
            <%= f.submit 'コメントを投稿する', class: 'btn btn-round btn-d' %>
          <% end %>
        </div>
      </div>
      
      <%= render 'layouts/sidebar' %>
      
    </div>
  </div>
</section>

app/views/topics/topics.html.erb
<% content_for :cover do %>
<section class="module bg-dark-30 about-page-header" data-background="assets/images/about_bg.jpg">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <h1 class="module-title font-alt mb-0">Tabs &amp; Accordions</h1>
      </div>
    </div>
  </div>
</section>
<% end %>

<section class="module">
  <div class="container">
    <div class="row">
      <div class="col-sm-8">
        <h4 class="font-alt mb-0">Topics</h4>
        <hr class="divider-w mt-10 mb-20">
        <div role="tabpanel">
          <% if @topics %>
            <ul class="nav nav-tabs font-alt" role="tablist">
              <li class="<%= 'active' if current_page?(topics_path(@topic)) %>"><%= link_to topics_path(@topic) do %>人気トピック <span class="badge"><%#= @count_topics %></span><% end %></li>
              <li class="<%= 'active' if current_page?(newtopics_topic_path(@topic)) %>"><%= link_to newtopics_topic_path(@topic) do %>新着トピック <span class="badge"><%#= @count_topics %></span><% end %></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active" id="support">
                <%= render 'topics', topics: @topics %>
              </div>
            </div>
          <% end %>
        </div>
        
        <div class="comment-form">
          <h4 class="comment-form-title font-alt">トピックの投稿</h4>
          <%= form_for(@topic) do |f| %>
            <div class="form-group">
              <%= f.label :title, 'タイトル', class: 'sr-only' %>
              <%= f.text_field :title, class: 'form-control', placeholder: 'タイトルを書く' %>
            </div>
            <div class="form-group">
              <%= f.label :content, '内容', class: 'sr-only' %>
              <%= f.text_area :content, class: 'form-control', placeholder: '本文を書く', :rows => "4" %>
            </div>
            <div class="form-group">
              <%= f.label :picture, '画像', class: 'sr-only' %>
              <%= f.file_field :picture, id: :topic_picture %>
              <%= f.hidden_field :picture_cache %>
            </div>
            <%= f.submit 'トピックを投稿する', class: 'btn btn-round btn-d' %>
          <% end %>
        </div>
      </div>
      
      
      <%# サイドバー %>
      <div class="col-sm-4 col-md-3 col-md-offset-1 sidebar">
        <div class="widget">
          <form role="form">
            <div class="search-box">
                <%= form_tag(topics_path, method: "get") do %>
                  <div class="input-group">
                    
                  	<%= text_field_tag :title, params[:title], class: 'form-control', placeholder: "トピックを検索" %>
                  	<span class="input-group-btn">
                      <%= button_tag( class: "btn btn-default") do %>
                        <%= content_tag(:i, '', class: 'fa fa-search') %>
                      <% end %>
                      
                  	  <%#= submit_tag '検索', class: 'btn btn-default' %>
                  	  
                  	</span>
                  </div>
                <% end %>
            </div>
          </form>
        </div>
        
        <div class="widget">
          <h5 class="widget-title font-alt">人気トピック</h5>
            <ul class="widget-posts">
              <% if @ranking_topics.present? %>
                <% @ranking_topics.each_with_index do |topic, index| %>
                  <li class="clearfix">
                    <div class="widget-posts-image">
                      <%=  link_to image_tag(topic.picture, size: 100), topic_path(topic) %>
                    </div>
                    <div class="widget-posts-body">
                      <div class="widget-posts-title">
                        <%= topic.title %>
                      </div>
                      <div class="widget-posts-meta">
                        <%= @ranking_counts[topic.id] %>コメント
                      </div>
                    </div>
                  </li>
                <% end %>
              <% end %>
            </ul>
        </div>
        
        <div class="widget">
          <h5 class="widget-title font-alt">新着トピック</h5>
            <ul class="widget-posts">
              <% if @new_topics.present? %>
                <% @new_topics.each do |topic| %>
                  <li class="clearfix">
                    <div class="widget-posts-image">
                      <%=  link_to image_tag(topic.picture, size: 100), topic_path(topic) %>
                    </div>
                    <div class="widget-posts-body">
                      <div class="widget-posts-title">
                        <%= topic.title %>
                      </div>
                      <div class="widget-posts-meta">
                        <%= topic.created_at.strftime('%Y/%m/%d %H:%M') %>
                      </div>
                    </div>
                  </li>
                <% end %>
              <% end %>
            </ul>
        </div>
        
      </div>
      <%# サイドバーここまで %>
      
    </div>
  </div>
</section>