config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get :favoritings
      get :entries
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  
  resources :topics do
    member do
      resources :posts
    end
  end
  
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  
end

app/models/user.rb
class User < ApplicationRecord
  
  scope :get_by_name, ->(name) {
  where("name like ?", "%#{name}%")
  }

  scope :get_by_age, ->(age) {
  where(age: age)
  }
  
  scope :get_by_live, ->(live) {
  where("live like ?", "%#{live}%")
  }
  
  scope :get_by_hobby, ->(hobby) {
  where(hobby: hobby)
  }
  
  mount_uploader :image, ImageUploader
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true, length: { maximum: 50 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :age, presence: true
  validates :hobby, presence: true
  validates :image, presence: true
  validates :pr, presence: true, length: { maximum: 300 }
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  has_many :topics,dependent: :destroy
  has_many :posts,dependent: :destroy
  
  has_many :favorites
  has_many :favoritings, through: :favorites, source: :topic
  
  has_many :messages,dependent: :destroy
  has_many :entries,dependent: :destroy
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def like(topic)
      self.favorites.find_or_create_by(topic_id: topic.id)
  end

  def unlike(topic)
    favorite = self.favorites.find_by(topic_id: topic.id)
    favorite.destroy if favorite
  end

  def liking?(topic)
    self.favoritings.include?(topic)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :followings, :followers]
  
  def index
    @users = User.all.page(params[:page])
    
    if params[:name].present? 
    @users = @users.get_by_name params[:name]
    end
    if params[:age].present?
    @users = @users.get_by_age params[:age]
    end
    if params[:live].present?
    @users = @users.get_by_live params[:live]
    end
    if params[:hobby].present?
    @users = @users.get_by_hobby params[:hobby]
    end
  end
  
  def show
    @user = User.find(params[:id])
    @topics = @user.topics.order('created_at DESC').page(params[:page])
    @followings = @user.followings.page(params[:page])
    @followers = @user.followers.page(params[:page])
    @favoritings = @user.favoritings.page(params[:page])
    @entries = @user.entries.page(params[:page])
    @ranking_counts = Post.ranking
    
    counts(@user)
    
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
          end
        end
      end
      if @isRoom
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id then
              @roomId = cu.room_id
            end
          end
        end
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def favoritings
    @user = User.find(params[:id])
    @favoritings = @user.favoritings.page(params[:page])
  end
  
  def entries
    @user = User.find(params[:id])
    @entries = @user.entries.page(params[:page])
    counts(@user)
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :age, :live, :hobby, :image, :pr)
  end
  
end

app/views/users/_entry.html.erb
<% if entries.any? %>
  <% entries.each do |entry| %>
    <div class="tab-pane" id="reviews">
      <div class="comments reviews">
        <div class="comment clearfix">
          <div class="comment-avatar">
            <%=  link_to image_tag(@user.image, size: 100), room_path(entry.room) %>
          </div>
          <div class="comment-content clearfix">
            <div class="comment-author font-alt">
              <%= link_to entry.room.id, room_path(entry.room) %>
            </div>
            <div class="comment-author font-alt">
              <%#= link_to @user.message.content, room_path(user.room) %>
            </div>
            <div class="comment-meta font-alt">
              <span><i class="fa fa-star star"></i></span><span><i class="fa fa-star star"></i></span><span><i class="fa fa-star star"></i></span><span><i class="fa fa-star star"></i></span><span><i class="fa fa-star star-off"></i></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%#= paginate @followings %>
<% else %>
  <p class="text-center" style="margin-top:30px;" >メッセージはありません</p>
<% end %>

app/views/users/_favorite.html.erb
<% if topics.present? %>
  <% topics.each do |topic| %>
    <div class="tab-pane" id="reviews">
      <div class="comments reviews">
        <div class="comment clearfix">
          <div class="comment-avatar">
            <%=  link_to image_tag(topic.picture, size: 100), topic_path(topic) %>
          </div>
          <div class="comment-content clearfix">
            <div class="comment-author font-alt">
              <%= topic.title %>
            </div>
            <div class="comment-body">
              <p><%= topic.content %></p>
            </div>
            <div class="comment-meta font-alt">
              <%= topic.created_at.strftime('%Y/%m/%d %H:%M') %> - <span><%= @ranking_counts[topic.id] %>コメント</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%#= paginate @topics %>
<% else %>
  <p class="text-center" style="margin-top:30px;" >登録トピックはありません</p>
<% end %>

app/views/users/_follow.html.erb
<% if users.any? %>
  <% users.each do |user| %>
    <div class="tab-pane" id="reviews">
      <div class="comments reviews">
        <div class="comment clearfix">
          <div class="comment-avatar">
            <%=  link_to image_tag(user.image, size: 100), user_path(user) %>
          </div>
          <div class="comment-content clearfix">
            <div class="comment-author font-alt">
              <%= link_to user.name, user_path(user) %>
            </div>
            <div class="comment-body">
              <p><%= user.age %> / <%= user.live %> / <%= user.hobby %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%#= paginate @followings %>
<% else %>
  <p class="text-center" style="margin-top:30px;" >フォローユーザーはいません</p>
<% end %>

app/views/users/_follower.html.erb
<% if users.any? %>
  <% users.each do |user| %>
    <div class="tab-pane" id="reviews">
      <div class="comments reviews">
        <div class="comment clearfix">
          <div class="comment-avatar">
            <%=  link_to image_tag(user.image, size: 100), user_path(user) %>
          </div>
          <div class="comment-content clearfix">
            <div class="comment-author font-alt">
              <%= link_to user.name, user_path(user) %>
            </div>
            <div class="comment-body">
              <p><%= user.age %> / <%= user.live %> / <%= user.hobby %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%#= paginate @followings %>
<% else %>
  <p class="text-center" style="margin-top:30px;" >フォロワーユーザーはいません</p>
<% end %>

app/views/users/_topic.html.erb
<% if topics.present? %>
  <% topics.each do |topic| %>
    <div class="tab-pane" id="reviews">
      <div class="comments reviews">
        <div class="comment clearfix">
          <div class="comment-avatar">
            <%=  link_to image_tag(topic.picture, size: 100), topic_path(topic) %>
          </div>
          <div class="comment-content clearfix">
            <div class="comment-author font-alt">
              <%= topic.title %>
            </div>
            <div class="comment-body">
              <p><%= topic.content %></p>
            </div>
            <div class="comment-meta font-alt">
              <%= topic.created_at.strftime('%Y/%m/%d %H:%M') %> - <span><%= @ranking_counts[topic.id] %>コメント</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%#= paginate @topics %>
<% else %>
  <p class="text-center" style="margin-top:30px;" >投稿トピックはありません</p>
<% end %>

app/views/users/_users.html.erb
<section class="module-small">
  <div class="container">
    <%= form_tag(users_path, method: "get", class: "row") do %>
      <div class="col-sm-3 mb-sm-20">
        <%= select_tag :age, options_for_select(["12歳以下", 
        "13", 
        "14", 
        "15", 
        "16", 
        "17", 
        "18", 
        "19", 
        "20", 
        "21", 
        "22", 
        "23", 
        "24", 
        "25", 
        "26", 
        "27", 
        "28", 
        "29", 
        "30", 
        "31", 
        "32", 
        "33", 
        "34", 
        "35", 
        "36", 
        "37", 
        "38", 
        "39", 
        "40", 
        "41", 
        "42", 
        "43", 
        "44", 
        "45", 
        "46", 
        "47", 
        "48", 
        "49", 
        "50", 
        "51", 
        "52", 
        "53", 
        "54", 
        "55", 
        "56", 
        "57", 
        "58", 
        "59", 
        "60", 
        "61", 
        "62", 
        "63", 
        "64", 
        "65歳以上"]), class: 'form-control', include_blank: true %>
      </div>
      <div class="col-sm-3 mb-sm-20">
        <%= select_tag :live, options_for_select(["北海道", 
        "青森県", 
        "岩手県", 
        "宮城県", 
        "秋田県", 
        "山形県", 
        "福島県", 
        "茨城県", 
        "栃木県", 
        "群馬県", 
        "埼玉県", 
        "千葉県", 
        "東京都", 
        "神奈川県", 
        "新潟県", 
        "富山県", 
        "石川県", 
        "福井県", 
        "山梨県", 
        "長野県", 
        "岐阜県", 
        "静岡県", 
        "愛知県", 
        "三重県", 
        "滋賀県", 
        "京都府", 
        "大阪府", 
        "兵庫県", 
        "奈良県", 
        "和歌山県", 
        "鳥取県", 
        "島根県", 
        "岡山県", 
        "広島県", 
        "山口県", 
        "徳島県", 
        "香川県", 
        "愛媛県", 
        "高知県", 
        "福岡県", 
        "佐賀県", 
        "長崎県", 
        "熊本県", 
        "大分県", 
        "宮崎県", 
        "鹿児島県", 
        "沖縄県", 
        "海外"]), class: 'form-control', include_blank: true %>
      </div>
      <div class="col-sm-3 mb-sm-20">
        <%= select_tag :hobby, options_for_select(["映画", 
        "ドラマ", 
        "アニメ", 
        "YouTube", 
        "ジャニーズ", 
        "韓流", 
        "漫画", 
        "読書", 
        "ゲーム", 
        "カメラ", 
        "旅行", 
        "ツーリング", 
        "ドライブ", 
        "ダンス", 
        "水泳", 
        "エクササイズ", 
        "スポーツ", 
        "料理", 
        "ピアノ", 
        "ギター", 
        "カラオケ", 
        "音楽", 
        "手芸", 
        "絵画", 
        "ペット", 
        "ブログ", 
        "SNS", 
        "ファッション", 
        "コスプレ", 
        "BL", 
        "その他"]), class: 'form-control', include_blank: true %>
      </div>

      <div class="col-sm-3">
        <%= submit_tag 'Search...', class: 'btn btn-block btn-round btn-g' %>
      </div>
    <% end %>
  </div>
</section>

<hr class="divider-w">

<section class="module-small">
  <% if users.any? %>
  <div class="container">
    <div class="row multi-columns-row">
      
      <% users.each do |user| %>
   
      <div class="col-sm-6 col-md-3 col-lg-3">
        <div class="shop-item">
          <div class="shop-item-image">
            <%=  link_to image_tag(user.image), user_path(user) %>
          </div>
          <h4 class="shop-item-title font-alt">
            <%= user.name %>
          </h4>
          <%= user.age %> / <%= user.live %> / <%= user.hobby %>
        </div>
      </div>
    
      <% end %>

    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="pagination font-alt"><a href="#"><i class="fa fa-angle-left"></i></a><a class="active" href="#">1</a><a href="#">2</a><a href="#">3</a><a href="#">4</a><a href="#"><i class="fa fa-angle-right"></i></a></div>
      </div>
    </div>
  </div>
  <% end %>
</section>

app/views/users/entries.html.erb
<section class="module">
  <div class="container">
    
    <div class="row">
      <div class="col-sm-6 mb-sm-40">
        <div id="gallery-user">
        <%= image_tag(@user.image, { :class => "gallery" }) %>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="row">
          <div class="col-sm-12">
            <h1 class="product-title font-alt"><%= @user.name %></h1>
          </div>
        </div>
        <div class="row mb-20">
          <div class="col-sm-12">
            <span><i class="fa fa-star star"></i></span><span><i class="fa fa-star star"></i></span><span><i class="fa fa-star star"></i></span><span><i class="fa fa-star star"></i></span><span><i class="fa fa-star star-off"></i></span><a class="open-tab section-scroll" href="#reviews">-2customer reviews</a>
          </div>
        </div>
        <div class="row mb-20">
          <div class="col-sm-12">
            <div class="price font-alt"><span class="amount"><%= @user.age %> / <%= @user.live %> / <%= @user.hobby %></span></div>
          </div>
        </div>
        <div class="row mb-20">
          <div class="col-sm-12">
            <%= render 'rooms/room_button' %>
          </div>
        </div>
        <div class="row mb-20">
          <div class="col-sm-12">
            <div class="description">
              <p><%= @user.pr %></p>
              <%= render 'relationships/follow_button', user: @user %>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <div class="row mt-70">
      <div class="col-sm-12">
        <ul class="nav nav-tabs font-alt" role="tablist">
          <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>トピック <span class="badge"><%= @count_topics %></span><% end %></li>
          <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>お気に入り <span class="badge"><%= @count_followings %></span><% end %></li>
          <% if @user == current_user %>
            <li class="<%= 'active' if current_page?(entries_user_path(@user)) %>"><%= link_to entries_user_path(@user) do %>メッセージ <span class="badge"><%= @count_entries %></span><% end %></li>
          <% end %>
          <%# <li><a href="#reviews" data-toggle="tab"><span class="icon-tools-2"></span>コメント (2)</a></li> %>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="description">
          <%= render 'entry', entries: @entries %>
          </div>
        </div>
      </div>
    </div>
    
  </div>
</section>

app/views/users/followings.html.erb
<section class="module">
  <div class="container">
    
    <div class="row">
      <div class="col-sm-6 mb-sm-40">
        <div id="gallery-user">
        <%= image_tag(@user.image, { :class => "gallery" }) %>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="row">
          <div class="col-sm-12">
            <h1 class="product-title font-alt"><%= @user.name %></h1>
          </div>
        </div>
        <div class="row mb-20">
          <div class="col-sm-12">
            <span><i class="fa fa-star star"></i></span><span><i class="fa fa-star star"></i></span><span><i class="fa fa-star star"></i></span><span><i class="fa fa-star star"></i></span><span><i class="fa fa-star star-off"></i></span><a class="open-tab section-scroll" href="#reviews">-2customer reviews</a>
          </div>
        </div>
        <div class="row mb-20">
          <div class="col-sm-12">
            <div class="price font-alt"><span class="amount"><%= @user.age %> / <%= @user.live %> / <%= @user.hobby %></span></div>
          </div>
        </div>
        <div class="row mb-20">
          <div class="col-sm-12">
            <%= render 'rooms/room_button' %>
          </div>
        </div>
        <div class="row mb-20">
          <div class="col-sm-12">
            <div class="description">
              <p><%= @user.pr %></p>
              <%= render 'relationships/follow_button', user: @user %>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <div class="row mt-70">
      <div class="col-sm-12">
        <ul class="nav nav-tabs font-alt" role="tablist">
          <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>トピック <span class="badge"><%= @count_topics %></span><% end %></li>
          <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>お気に入り <span class="badge"><%= @count_followings %></span><% end %></li>
          <% if @user == current_user %>
            <li class="<%= 'active' if current_page?(entries_user_path(@user)) %>"><%= link_to entries_user_path(@user) do %>メッセージ <span class="badge"><%= @count_entries %></span><% end %></li>
          <% end %>
          <%# <li><a href="#reviews" data-toggle="tab"><span class="icon-tools-2"></span>コメント (2)</a></li> %>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="description">
          <%= render 'follow', users: @followings %>
          </div>
        </div>
      </div>
    </div>
    
  </div>
</section>

app/views/users/index.html.erb
<% content_for :cover do %>
  <section class="module bg-dark-30 about-page-header" data-background="assets/images/about_bg.jpg">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h1 class="module-title font-alt mb-0">Forms</h1>
        </div>
      </div>
    </div>
  </section>
<% end %>

<%= render 'users/users', users: @users %>

app/views/users/new.html.erb
<% content_for :cover do %>
  <section class="module bg-dark-30 about-page-header" data-background="assets/images/about_bg.jpg">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h1 class="module-title font-alt mb-0">Forms</h1>
        </div>
      </div>
    </div>
  </section>
<% end %>

<section class="module">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <h4 class="font-alt mb-0">新規登録</h4>
        <hr class="divider-w mt-10 mb-20">
        <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'お名前', class: 'sr-only' %>
            <%= f.text_field :name, class: 'form-control', placeholder: 'お名前' %>
          </div>
          <div class="form-group">
            <%= f.label :email, 'メールアドレス', class: 'sr-only' %>
            <%= f.email_field :email, class: 'form-control', placeholder: 'メールアドレス' %>
          </div>
          <div class="form-group">
            <%= f.label :password, 'パスワード', class: 'sr-only' %>
            <%= f.password_field :password, class: 'form-control', placeholder: 'パスワード' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）', class: 'sr-only' %>
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'パスワード（確認）' %>
          </div>
          
          <div class="form-group">
            <%= f.label :age, '年齢', class: 'sr-only' %>
            <%= f.select :age, [["12歳以下", "12歳以下"],
            ["13", "13"], 
            ["14", "14"], 
            ["15", "15"], 
            ["16", "16"], 
            ["17", "17"], 
            ["18", "18"], 
            ["19", "19"], 
            ["20", "20"], 
            ["21", "21"], 
            ["22", "22"], 
            ["23", "23"], 
            ["24", "24"], 
            ["25", "25"], 
            ["26", "26"], 
            ["27", "27"], 
            ["28", "28"], 
            ["29", "29"], 
            ["30", "30"], 
            ["31", "31"], 
            ["32", "32"], 
            ["33", "33"], 
            ["34", "34"], 
            ["35", "35"], 
            ["36", "36"], 
            ["37", "37"], 
            ["38", "38"], 
            ["39", "39"], 
            ["40", "40"], 
            ["41", "41"], 
            ["42", "42"], 
            ["43", "43"], 
            ["44", "44"], 
            ["45", "45"], 
            ["46", "46"], 
            ["47", "47"], 
            ["48", "48"], 
            ["49", "49"], 
            ["50", "50"], 
            ["51", "51"], 
            ["52", "52"], 
            ["53", "53"], 
            ["54", "54"], 
            ["55", "55"], 
            ["56", "56"], 
            ["57", "57"], 
            ["58", "58"], 
            ["59", "59"], 
            ["60", "60"], 
            ["61", "61"], 
            ["62", "62"], 
            ["63", "63"], 
            ["64", "64"], 
            ["65歳以上", "65歳以上"]] , class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :live, '住まい', class: 'sr-only' %>
            <%= f.select :live, [["北海道", "北海道"], 
            ["青森県", "青森県"], 
            ["岩手県", "岩手県"], 
            ["宮城県", "宮城県"], 
            ["秋田県", "秋田県"], 
            ["山形県", "山形県"], 
            ["福島県", "福島県"], 
            ["茨城県", "茨城県"], 
            ["栃木県", "栃木県"], 
            ["群馬県", "群馬県"], 
            ["埼玉県", "埼玉県"], 
            ["千葉県", "千葉県"], 
            ["東京都", "東京都"], 
            ["神奈川県", "神奈川県"], 
            ["新潟県", "新潟県"], 
            ["富山県", "富山県"], 
            ["石川県", "石川県"], 
            ["福井県", "福井県"], 
            ["山梨県", "山梨県"], 
            ["長野県", "長野県"], 
            ["岐阜県", "岐阜県"], 
            ["静岡県", "静岡県"], 
            ["愛知県", "愛知県"], 
            ["三重県", "三重県"], 
            ["滋賀県", "滋賀県"], 
            ["京都府", "京都府"], 
            ["大阪府", "大阪府"], 
            ["兵庫県", "兵庫県"], 
            ["奈良県", "奈良県"], 
            ["和歌山県", "和歌山県"], 
            ["鳥取県", "鳥取県"], 
            ["島根県", "島根県"], 
            ["岡山県", "岡山県"], 
            ["広島県", "広島県"], 
            ["山口県", "山口県"], 
            ["徳島県", "徳島県"], 
            ["香川県", "香川県"], 
            ["愛媛県", "愛媛県"], 
            ["高知県", "高知県"], 
            ["福岡県", "福岡県"], 
            ["佐賀県", "佐賀県"], 
            ["長崎県", "長崎県"], 
            ["熊本県", "熊本県"], 
            ["大分県", "大分県"], 
            ["宮崎県", "宮崎県"], 
            ["鹿児島県", "鹿児島県"], 
            ["沖縄県", "沖縄県"], 
            ["海外", "海外"]] , class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :hobby, '趣味', class: 'sr-only' %>
            <%= f.select :hobby, [["映画", "映画"], 
            ["ドラマ", "ドラマ"], 
            ["アニメ", "アニメ"], 
            ["YouTube", "YouTube"], 
            ["ジャニーズ", "ジャニーズ"], 
            ["韓流", "韓流"], 
            ["漫画", "漫画"], 
            ["読書", "読書"], 
            ["ゲーム", "ゲーム"], 
            ["カメラ", "カメラ"], 
            ["旅行", "旅行"], 
            ["ツーリング", "ツーリング"], 
            ["ドライブ", "ドライブ"], 
            ["ダンス", "ダンス"], 
            ["水泳", "水泳"], 
            ["エクササイズ", "エクササイズ"], 
            ["スポーツ", "スポーツ"], 
            ["料理", "料理"], 
            ["ピアノ", "ピアノ"], 
            ["ギター", "ギター"], 
            ["カラオケ", "カラオケ"], 
            ["音楽", "音楽"], 
            ["手芸", "手芸"], 
            ["絵画", "絵画"], 
            ["ペット", "ペット"], 
            ["ブログ", "ブログ"], 
            ["SNS", "SNS"], 
            ["ファッション", "ファッション"], 
            ["コスプレ", "コスプレ"], 
            ["BL", "BL"], 
            ["その他", "その他"]] , class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :image, '画像', class: 'sr-only' %>
            <%= f.file_field :image, id: :user_image %>
            <%= f.hidden_field :image_cache %>
          </div>
          
          <div class="form-group">
            <%= f.label :pr, '自己紹介', class: 'sr-only' %>
            <%= f.text_area :pr, class: 'form-control', placeholder: '自己紹介', :rows => "7" %>
          </div>
          
          <div class="form-group">
            <%= f.submit '登録する', class: 'btn btn-round btn-g' %>
          </div>
          
        <% end %>
      </div>
    </div>
  </div>
</section>