config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get :favoritings
      get :entries
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  
  resources :topics do
    member do
      resources :posts
    end
  end
  
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="module-small bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="widget">
          <h5 class="widget-title font-alt">About Titan</h5>
          <p>The languages only differ in their grammar, their pronunciation and their most common words.</p>
          <p>Phone: +1 234 567 89 10</p>Fax: +1 234 567 89 10
          <p>Email:<a href="#">somecompany@example.com</a></p>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="widget">
          <h5 class="widget-title font-alt">Recent Comments</h5>
          <ul class="icon-list">
            <li>Maria on <a href="#">Designer Desk Essentials</a></li>
            <li>John on <a href="#">Realistic Business Card Mockup</a></li>
            <li>Andy on <a href="#">Eco bag Mockup</a></li>
            <li>Jack on <a href="#">Bottle Mockup</a></li>
            <li>Mark on <a href="#">Our trip to the Alps</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="widget">
          <h5 class="widget-title font-alt">Blog Categories</h5>
          <ul class="icon-list">
            <li><a href="#">Photography - 7</a></li>
            <li><a href="#">Web Design - 3</a></li>
            <li><a href="#">Illustration - 12</a></li>
            <li><a href="#">Marketing - 1</a></li>
            <li><a href="#">Wordpress - 16</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="widget">
          <h5 class="widget-title font-alt">Popular Posts</h5>
          <ul class="widget-posts">
            <li class="clearfix">
              <div class="widget-posts-image"><a href="#"><img src="assets/images/rp-1.jpg" alt="Post Thumbnail"/></a></div>
              <div class="widget-posts-body">
                <div class="widget-posts-title"><a href="#">Designer Desk Essentials</a></div>
                <div class="widget-posts-meta">23 january</div>
              </div>
            </li>
            <li class="clearfix">
              <div class="widget-posts-image"><a href="#"><img src="assets/images/rp-2.jpg" alt="Post Thumbnail"/></a></div>
              <div class="widget-posts-body">
                <div class="widget-posts-title"><a href="#">Realistic Business Card Mockup</a></div>
                <div class="widget-posts-meta">15 February</div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<hr class="divider-d">

<footer class="footer bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <p class="copyright font-alt">&copy; 2017&nbsp;<a href="index.html">TitaN</a>, All Rights Reserved</p>
      </div>
      <div class="col-sm-6">
        <div class="footer-social-links"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-dribbble"></i></a><a href="#"><i class="fa fa-skype"></i></a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#custom-collapse"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a class="navbar-brand" href="/">Titan</a>
    </div>
    <div class="collapse navbar-collapse" id="custom-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        
        <li>
          <%= link_to 'Topics', topics_path%>
        </li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </a>
          
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'My page', user_path(current_user) %>
            </li>
            <li>
              <%= link_to 'Log out', logout_path, method: :delete %>
            </li>
          </ul>
        </li>

        <% else %>
          <li><%= link_to '新規登録', signup_path %></li>
          <li><%= link_to 'ログイン', login_path %></li>
        <% end %>
      </ul>
     
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="col-sm-4 col-md-3 col-md-offset-1 sidebar">
  <div class="widget">

      <%= link_to new_topic_path, class: 'btn btn-round btn-d btn-lg'  do %>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        トピックを投稿する
      <% end %>
    
  </div>
  
  <div class="widget">
    <h5 class="widget-title font-alt">人気トピック</h5>
      <ul class="widget-posts">
        <% if @ranking_topics.present? %>
          <% @ranking_topics.each_with_index do |topic, index| %>
            <li class="clearfix">
              <div class="widget-posts-image">
                <%=  link_to image_tag(topic.picture, size: 100), topic_path(topic) %>
              </div>
              <div class="widget-posts-body">
                <div class="widget-posts-title">
                  <%= topic.title %>
                </div>
                <div class="widget-posts-meta">
                  <%= @ranking_counts[topic.id] %>コメント
                </div>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
  </div>
  
  <div class="widget">
    <h5 class="widget-title font-alt">新着トピック</h5>
      <ul class="widget-posts">
        <% if @new_topics.present? %>
          <% @new_topics.each do |topic| %>
            <li class="clearfix">
              <div class="widget-posts-image">
                <%=  link_to image_tag(topic.picture, size: 100), topic_path(topic) %>
              </div>
              <div class="widget-posts-body">
                <div class="widget-posts-title">
                  <%= topic.title %>
                </div>
                <div class="widget-posts-meta">
                  <%= topic.created_at.strftime('%Y/%m/%d %H:%M') %>
                </div>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>女子トモ</title>
    <%= csrf_meta_tags %>
    
    <!-- Favicons-->
    <link rel="apple-touch-icon" sizes="57x57" href="assets/images/favicons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="assets/images/favicons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="assets/images/favicons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="assets/images/favicons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="assets/images/favicons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="assets/images/favicons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="assets/images/favicons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="assets/images/favicons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="assets/images/favicons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="assets/images/favicons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="assets/images/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="assets/images/favicons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicons/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="assets/images/favicons/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <!--  
    Stylesheets
    =============================================
    
    -->
    <!-- Default stylesheets-->
    <%= stylesheet_link_tag  'lib/bootstrap/dist/css/bootstrap.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Template specific stylesheets-->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Volkhov:400i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    
    <%= stylesheet_link_tag  'lib/animate.css/animate', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  'lib/components-font-awesome/css/font-awesome.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  'lib/et-line-font/et-line-font', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  'lib/flexslider/flexslider', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  'lib/owl.carousel/dist/assets/owl.carousel.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  'lib/owl.carousel/dist/assets/owl.theme.default.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  'lib/magnific-popup/dist/magnific-popup', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  'lib/simple-text-rotator/simpletextrotator', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <!-- Main stylesheet and color file-->
    <%= stylesheet_link_tag  'css/style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  'css/colors/default', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS-->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
    <!-- app/assets/stylesheets -->
    <%#= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <!-- app/assets/javascripts-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap JavaScript-->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
    
    <!--  
    JavaScripts
    =============================================
    -->
    <script src="assets/lib/jquery/dist/jquery.js"></script>
    <script src="assets/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="assets/lib/wow/dist/wow.js"></script>
    <script src="assets/lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js"></script>
    <script src="assets/lib/isotope/dist/isotope.pkgd.js"></script>
    <script src="assets/lib/imagesloaded/imagesloaded.pkgd.js"></script>
    <script src="assets/lib/flexslider/jquery.flexslider.js"></script>
    <script src="assets/lib/owl.carousel/dist/owl.carousel.min.js"></script>
    <script src="assets/lib/smoothscroll.js"></script>
    <script src="assets/lib/magnific-popup/dist/jquery.magnific-popup.js"></script>
    <script src="assets/lib/simple-text-rotator/jquery.simple-text-rotator.min.js"></script>
    <script src="assets/js/plugins.js"></script>
    <script src="assets/js/main.js"></script>
    
  </head>
  
  <body data-spy="scroll" data-target=".onpage-navigation" data-offset="60">
    <main>
      <%= render 'layouts/navbar' %>
      <div class="main">
        <%= yield :cover %>
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
        <%= render 'layouts/footer' %>
      </div>
      <div class="scroll-up"><a href="#totop"><i class="fa fa-angle-double-up"></i></a></div>
    </main>
  </body>
</html>